jwt:
  signing-key: ${JWT_KEY:test_key_bsc_skol}

swagger:
  admin:
    login: ${SWAGGER_ADMIN:admin}
    password: ${SWAGGER_PASSWORD:bcs-recommended}

spring:
  data:
    mongodb:
      uri: mongodb+srv://BCSAdmin:qWWp@7pgE3hZ@cluster0.mrofz.mongodb.net/bcsdb?retryWrites=true&w=majority
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
      indent-output: true
